Update openwrt-ci.yml

diff --git a/.github/workflows/openwrt-ci.yml b/.github/workflows/openwrt-ci.yml
--- a/.github/workflows/openwrt-ci.yml
+++ b/.github/workflows/openwrt-ci.yml
@@ -52,18 +52,18 @@ jobs:
           #清空缓存
           clean: false
           
-      - name: Space cleanup
-        env:
-          DEBIAN_FRONTEND: noninteractive
-        run: |
-          docker rmi `docker images -q`
-          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
-          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
-          sudo -E apt-get update
-          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
-          sudo -E apt-get -y autoremove --purge
-          sudo -E apt-get clean
-          df -h
+#       - name: Space cleanup
+#         env:
+#           DEBIAN_FRONTEND: noninteractive
+#         run: |
+#           docker rmi `docker images -q`
+#           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
+#           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
+#           sudo -E apt-get update
+#           sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
+#           sudo -E apt-get -y autoremove --purge
+#           sudo -E apt-get clean
+#           df -h
           
       - name: SSH connection to Actions
         uses: P3TERX/ssh2actions@v1.0.0
@@ -88,13 +88,14 @@ jobs:
           cat target/linux/ramips/Makefile
           make defconfig
 
-      - name: Make download
-        run: |
-          make download -j8
-          find dl -size -1024c -exec rm -f {} \;
+#       - name: Make download
+#         run: |
+#           make download -j8
+#           find dl -size -1024c -exec rm -f {} \;
 
       - name: Compile firmware
         run: |
+          make clean
           make -j$(nproc) || make -j1 V=s
           echo "======================="
           echo "Space usage:"
